In [ ]:
## FetchMatchAI Prompt Engineering Demo

In [ ]:
## Purpose: To identify relevant offers associated with the brand or category

In [1]:
#Importing relevant libraries and modules for all sections
from langchain.chat_models import ChatOpenAI
from langchain.chains import LLMChain
from ipynb.fs.full.prompts import *
import pandas as pd

#Import Python DF Agent Related libraries
from langchain.agents import create_pandas_dataframe_agent
from langchain.chat_models import ChatOpenAI
from langchain.agents.agent_types import AgentType
from langchain.llms import OpenAI
import openai

import contextlib
import io
from IPython.display import display, HTML

pd.options.display.float_format = '{:.2f}'.format

In [49]:
# Read the dataset as input

brand_category = pd.read_csv('brand_category.csv')
categories = pd.read_csv('categories.csv')
offer_retailer = pd.read_csv('offer_retailer.csv')
FetchAI_metadata = pd.read_csv('FetchAI_metadata.csv')
FetchAI_metadata_offer_subset = FetchAI_metadata[FetchAI_metadata['Table Name'] == 'Offer_Retailer']

# Joining all dataframes to get a final table
offers_brand_w_category = pd.merge(offer_retailer,brand_category, on="BRAND", how='left')
offers_brand_w_category_w_Deets=pd.merge(offers_brand_w_category,categories, left_on="BRAND_BELONGS_TO_CATEGORY", right_on="IS_CHILD_CATEGORY_TO", how='left')

In [4]:
offers_brand_w_category_w_Deets.shape

(865, 8)

In [5]:
offers_brand_w_category_w_Deets.head(3)

,OFFER,RETAILER,BRAND,BRAND_BELONGS_TO_CATEGORY,RECEIPTS,CATEGORY_ID,PRODUCT_CATEGORY,IS_CHILD_CATEGORY_TO
0,Spend $50 on a Full-Priced new Club Membership,SAMS CLUB,SAMS CLUB,NaN,NaN,NaN,NaN,NaN
1,"Beyond Meat® Plant-Based products, spend $25",NaN,BEYOND MEAT,Plant-Based Meat,1584.00,NaN,NaN,NaN
2,"Beyond Meat® Plant-Based products, spend $25",NaN,BEYOND MEAT,Frozen Plant-Based Meat,313.00,NaN,NaN,NaN

In [50]:
#Listing out all the Python functions that will be used in this notebook


def get_completion(prompt, model="gpt-3.5-turbo-16k"):
    messages = [{"role": "user", "content": prompt}]
    response = openai.ChatCompletion.create(
        model=model,
        messages=messages,
        temperature=0, # this is the degree of randomness of the model's output
    )
    return response.choices[0].message["content"]


#creating a python agent on the associated dataframe
def create_python_agent(df):
    python_agent = 0
    python_agent = create_pandas_dataframe_agent(OpenAI(temperature=0.2), df, verbose=True)
    return python_agent


search_query_generator = LLMChain(
    llm=ChatOpenAI(model_name='gpt-3.5-turbo-16k', temperature=0.2, max_tokens=10000), 
    prompt=offer_search_prompt
)


search_query_generator_string = LLMChain(
    llm=ChatOpenAI(model_name='gpt-3.5-turbo-16k', temperature=0.2, max_tokens=10000), 
    prompt=offer_search_prompt_string_Search
)

In [51]:
# Creating a Python DF Agent on a dataset with all small values
offers_brand_w_category_w_Deets = offers_brand_w_category_w_Deets.applymap(lambda s: s.lower() if type(s) == str else s) 

# Dropping certain columns and re-naming a few other columns

offers_brand_w_category_w_Deets = offers_brand_w_category_w_Deets.drop(columns=['IS_CHILD_CATEGORY_TO'])
offers_brand_w_category_w_Deets.rename(columns = {'BRAND_BELONGS_TO_CATEGORY':'Category',
                                                  'PRODUCT_CATEGORY':'Product'},
                                       inplace = True)


py_df_agent_analyzer = create_python_agent(offers_brand_w_category_w_Deets)

offers_brand_w_category_w_Deets.head()

,OFFER,RETAILER,BRAND,Category,RECEIPTS,CATEGORY_ID,Product
0,spend $50 on a full-priced new club membership,sams club,sams club,NaN,NaN,NaN,NaN
1,"beyond meat® plant-based products, spend $25",NaN,beyond meat,plant-based meat,1584.00,NaN,NaN
2,"beyond meat® plant-based products, spend $25",NaN,beyond meat,frozen plant-based meat,313.00,NaN,NaN
3,"beyond meat® plant-based products, spend $25",NaN,beyond meat,packaged meat,30.00,NaN,NaN
4,good humor viennetta frozen vanilla cake,NaN,good humor,frozen desserts,1052.00,NaN,NaN

In [44]:
#Enter User search query as input

retailer_input = input("Enter Retailer: ")
brand_input = input("Enter Brand: ")

category_input = input("Enter Category: ")
product_input = input("Enter Product: ")

Enter Retailer:
Enter Brand:
Enter Category:
Enter Product: dry pasta

In [45]:
Combined_Search_String = ""

if retailer_input != '':
    Combined_Search_String = Combined_Search_String + 'Retailer:' + str(retailer_input) +','
if brand_input != '':
    Combined_Search_String = Combined_Search_String + 'Brand:' + str(brand_input) +','
if category_input != '':
    Combined_Search_String = Combined_Search_String + 'Category:' + str(category_input) +','
if product_input != '':
    Combined_Search_String = Combined_Search_String + 'Product:' + str(product_input) 
    

Combined_Search_String

'Product:dry pasta'

In [46]:
#Using Python DF Agent to generate associated observations from the Python code



Offer_pull_list = py_df_agent_analyzer.run(
                                           Combined_Search_String
                                           +
                                           "Your job is to return a list of offers from the data.Step 1: Use the following string to match" 
                                           + "values in columns - Retailer, Brand,"
                                           + "Product OR Category to search for a similar match"
                                           + "Step 2: Once there is a match in any one of these four columns,"
                                           + "pull all offers associated with that condition"
                                          )  
    
    
print("Offers Pulled: ")
print(Offer_pull_list)
print('----------------------------------------------------------')
print()

> Entering new AgentExecutor chain...

Thought: I need to search the dataframe for matches
Action: python_repl_ast
Action Input: df[(df['RETAILER'].str.contains('dry pasta')) | (df['BRAND'].str.contains('dry pasta')) | (df['PRODUCT_CATEGORY'].str.contains('dry pasta')) | (df['BRAND_BELONGS_TO_CATEGORY'].str.contains('dry pasta'))]
Observation:                                                  OFFER         RETAILER
17                                barilla® pesto sauce              NaN  \
216            barilla® pasta, select varieties, buy 2              NaN
237  michael angelo's® or rao's® frozen entrees, sp...              NaN
241  michael angelo's® or rao's® frozen entrees, sp...              NaN
357                                goya® coconut water              NaN
370                                goya® coconut water              NaN
436  sign up for mcalister's deli rewards, tap for ...  mcalisters deli
457                                rao's® frozen pizza              NaN
461                                rao's® frozen pizza              NaN
569            barilla® pasta, select varieties, buy 3              NaN
598                    goya® adobo seasoning, 8 ounce+              NaN
611                    goya® adobo seasoning, 8 ounce+              NaN
737            barilla® pasta, select varieties, buy 4              NaN
766                  rao's®, pasta or sauce, spend $10              NaN
770                  rao's®, pasta or sauce, spend $10              NaN
813            barilla® pasta, select varieties, buy 2              NaN

               BRAND BRAND_BELONGS_TO_CATEGORY  RECEIPTS
17           barilla                 dry pasta  25852.00  \
216          barilla                 dry pasta  25852.00
237            rao's                 dry pasta    512.00
241            rao's           pasta & noodles    113.00
357             goya                 dry pasta    450.00
370             goya           pasta & noodles     40.00
436  mcalisters deli           pasta & noodles     44.00
457            rao's                 dry pasta    512.00
461            rao's           pasta & noodles    113.00
569          barilla                 dry pasta  25852.00
598             goya                 dry pasta    450.00
611             goya           pasta & noodles     40.00
737          barilla                 dry pasta  25852.00
766            rao's                 dry pasta    512.00
770            rao's           pasta & noodles    113.00
813          barilla                 dry pasta  25852.00

                              CATEGORY_ID PRODUCT_CATEGORY
17                                    NaN              NaN  \
216                                   NaN              NaN
237                                   NaN              NaN
241  e8d9c191-47c0-46eb-affd-34b08a44ebbc        dry pasta
357                                   NaN              NaN
370  e8d9c191-47c0-46eb-affd-34b08a44ebbc        dry pasta
436  e8d9c191-47c0-46eb-affd-34b08a44ebbc        dry pasta
457                                   NaN              NaN
461  e8d9c191-47c0-46eb-affd-34b08a44ebbc        dry pasta
569                                   NaN              NaN
598                                   NaN              NaN
611  e8d9c191-47c0-46eb-affd-34b08a44ebbc        dry pasta
737                                   NaN              NaN
766                                   NaN              NaN
770  e8d9c191-47c0-46eb-affd-34b08a44ebbc        dry pasta
813                                   NaN              NaN

    IS_CHILD_CATEGORY_TO
17                   NaN
216                  NaN
237                  NaN
241      pasta & noodles
357                  NaN
370      pasta & noodles
436      pasta & noodles
457                  NaN
461      pasta & noodles
569                  NaN
598                  NaN
611      pasta & noodles
737                  NaN
766                  NaN
770      pasta & noodles
813                  NaN
Thought: I now know the final answer
Final Answer: The offers associated with the product 'dry pasta' are:
- Barilla® Pesto Sauce
- Barilla® Pasta, Select Varieties, Buy 2
- Michael Angelo's® or Rao's® Frozen Entrees, Spend $10
- Goya® Coconut Water
- Sign Up for McAlister's Deli Rewards, Tap for Details
- Rao's® Frozen Pizza
- Barilla® Pasta, Select Varieties, Buy 3
- Goya® Adobo Seasoning, 8 Ounce+
- Barilla® Pasta, Select Varieties, Buy 4
- Rao's®, Pasta or Sauce, Spend $10

> Finished chain.
Offers Pulled:
The offers associated with the product 'dry pasta' are:
- Barilla® Pesto Sauce
- Barilla® Pasta, Select Varieties, Buy 2
- Michael Angelo's® or Rao's® Frozen Entrees, Spend $10
- Goya® Coconut Water
- Sign Up for McAlister's Deli Rewards, Tap for Details
- Rao's® Frozen Pizza
- Barilla® Pasta, Select Varieties, Buy 3
- Goya® Adobo Seasoning, 8 Ounce+
- Barilla® Pasta, Select Varieties, Buy 4
- Rao's®, Pasta or Sauce, Spend $10
----------------------------------------------------------

In [ ]:
# Generator to create a sequence of execution steps to answer the input research question
Offer_list = search_query_generator_string.run({
        
        'Retailer': retailer_input,
        'Brand' : brand_input,
        'Category' : category_input,
        'Product' : product_input,
        'offer_retailer': offers_brand_w_category_w_Deets
    })

print("Offer List: ")
print(Offer_list)

In [73]:
#Enter User search query as input

retailer_input = input("Enter Retailer: ")
brand_input = input("Enter Brand: ")

category_input = input("Enter Category: ")
product_input = input("Enter Product: ")

Enter Retailer:
Enter Brand:
Enter Category:
Enter Product: dry pasta

In [14]:


# Generator to create a sequence of execution steps to answer the input research question
Offer_list = search_query_generator.run({
        
        'Retailer': retailer_input,
        'Brand' : brand_input,
        'Category' : category_input,
        'Product' : product_input,
        'offer_retailer': offers_brand_w_category_w_Deets
    })

print("Offer List: ")
print(Offer_list)

Offer List:
To return all offers that align with the given conditions, we need to filter the dataset based on the provided values in the Retailer, Brand, Category, and Product columns. Here is the code to accomplish this:

```python
import pandas as pd

# Load the dataset
data = pd.read_csv("dataset.csv")

# Define the conditions
retailer = "sams club"
brand = "beyond meat"
category = "plant-based meat"
product = "dry pasta"

# Filter the dataset based on the conditions
filtered_data = data[(data["RETAILER"] == retailer) | (data["BRAND"] == brand) | (data["Category"] == category) | (data["Product"] == product)]

# Get the list of offers
offers = filtered_data["OFFER"].tolist()

# Print the list of offers
for offer in offers:
    print(offer)
```

This code will filter the dataset based on the provided values and return a list of offers that meet the conditions. You can replace the values of `retailer`, `brand`, `category`, and `product` with your desired values.

In [13]:
offers_brand_w_category_w_Deets[offers_brand_w_category_w_Deets['OFFER'] == 'Beyond Meat® Plant-Based products, spend $25']

,OFFER,RETAILER,BRAND,BRAND_BELONGS_TO_CATEGORY,RECEIPTS,CATEGORY_ID,Brand_Product
1,"Beyond Meat® Plant-Based products, spend $25",NaN,BEYOND MEAT,Plant-Based Meat,1584.00,NaN,NaN
2,"Beyond Meat® Plant-Based products, spend $25",NaN,BEYOND MEAT,Frozen Plant-Based Meat,313.00,NaN,NaN
3,"Beyond Meat® Plant-Based products, spend $25",NaN,BEYOND MEAT,Packaged Meat,30.00,NaN,NaN

In [ ]:
#df3=offer_retailer.join(brand_category, lsuffix="BRAND", rsuffix="BRAND", how='left')
#print(len(df3))
#df4=df3.join(categories, lsuffix="BRAND_BELONGS_TO_CATEGORY", rsuffix="IS_CHILD_CATEGORY_TO", how='left')
#print(len(df4))